# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  release:
    docker:
      - image: circleci/node:10

    working_directory: /tmp/decentraland-ecs-utils

    steps:
      - checkout
      - run:
          name: Build library
          command: npm run make
      - run:
          name: Install dependencies
          command: cd dist && npm i
      - run:
          name: Semantic release
          command: cd dist && npm run semantic-release

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
